.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "OWATCHDETACHOP" "3" "12/17/2006" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
owatchDetachOp \- ...
.SH "SYNOPSIS"
\fB#include <optikus/watch.h>\fR
.sp
\fBoret_t owatchDetachOp (owop_t \fR\fB\fIop\fR\fR\fB)\fR;
.sp
.SH "DESCRIPTION"
This routine marks the \fIop\fR operation as \fBdetached\fR. There is no need to wait for such an operation. Its descririptor will be freed automatically when the operation completes. Trying to wait for the detached operation is allowed to fail.
.sp
.SH "RETURN VALUE"
The routine returns \fIOK\fR, if the operation descriptor was valid and occupied before the call. Otherwise, the routine returns \fIERROR\fR.
.sp
.SH "BUGS"
See the Optikus distribution BUGS file.
.sp
.SH "RESOURCES"
SourceForge: \fIhttp://sourceforge.net/projects/asciidoc\fR
.sp
Main web site: \fIhttp://optikus.sourceforge.net\fR
.sp
.SH "COPYING"
Copyright (C) 2006\-2007 vitki.net. The Optikus library is free software. You can redistribute and/or modify it under the the terms of the GNU General Public License (GPL).
.sp
